### ISSUE TITLE
documentation on how to add support?

### ISSUE THREAD

**Issue by samekmichal** [skynav/ttv#35]
Hi, would it be possible to briefly sketch out what needs to be done to add support to ttt-ttv for other TTML-based profile - EBU-TT-D
https://tech.ebu.ch/docs/tech/tech3380.pdf

Is that supposed to be done by extending the com.skynav.ttv.model.Profile.Specification class or by extending the TTML1.TTML1Model class (since it is subset of TTML1)?

Thanks.

**Comment by skynavga** [comment]
see support for other profiles as examples; also note that this repository has been moved to the ttt-ttv module under repository https://github.com/skynav/ttt

**Comment by samekmichal** [comment]
Yes, I had a look. But these profiles are supersets to TTML, right? However EBU-TT-D is a subset. The best would be to integrate the XSD schema for EBU-TT-D, and let JAXB generate classes. The disadvantage of this is that I will not be able to run TTML1 semantic verification on that, since the generated files will be different to the ones generated from TTML1 XSD....

**Comment by skynavga** [comment]
Take a close look at how the TTML2 model was implemented under the [new repository](https://github.com/skynav/ttt). You will see that a distinct XSD schema is used for TTML2, which, nevertheless, inherits much behavior from existing TTML1 code. Helper classes were added at various points to deal with the use of distinct JAXB packages containing the same named types.

**Comment by skynavga** [comment]
You could use the same approach with EBU-TT and implement subsetting in two parts: first in the subsetted schema you would employ, second in the various verifier logic.
